### List all messages
GET http://localhost:3000/messages


### POST messages
POST http://localhost:3000/messages
content-type: application/json

{
	"content": "my name is Alex"
}


### GET specific messsage
GET http://localhost:3000/messages/985




### DELETE specific messsage
DELETE http://localhost:3000/messages/985


### DELETE ALL messsages
DELETE http://localhost:3000/messages
