### List all messages
GET http://localhost:3000/messages


### POST messages
POST http://localhost:3000/messages
content-type: application/json

{
	"content": 123
}


### GET specific messsage
GET http://localhost:3000/messages/123
